# Generated by Django 4.2 on 2024-11-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=100)),
                ('ursid', models.CharField(default='', max_length=50)),
                ('demat', models.CharField(default='', max_length=25)),
                ('platform', models.CharField(default='', max_length=30)),
                ('company', models.CharField(default='', max_length=50)),
                ('shares', models.IntegerField(default=0)),
                ('buyprice', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='lic_insurance',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='LIC_Insurance',
        ),
    ]
