# Generated by Django 4.2 on 2024-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stocks_investment_remove_lic_insurance_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_loan',
            old_name='emi_amount',
            new_name='emi',
        ),
        migrations.RenameField(
            model_name='house_loan',
            old_name='bank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='house_loan',
            old_name='ifsc',
            new_name='power',
        ),
        migrations.RemoveField(
            model_name='house_loan',
            name='Date_of_sanction',
        ),
        migrations.RemoveField(
            model_name='house_loan',
            name='date_of_first_emi',
        ),
        migrations.RemoveField(
            model_name='house_loan',
            name='date_of_last_emi',
        ),
        migrations.RemoveField(
            model_name='house_loan',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='house_loan',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='house_loan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house_loan',
            name='term',
            field=models.CharField(default='', max_length=100),
        ),
    ]
