# Generated by Django 4.2 on 2024-11-03 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_card_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.DateField(default=0),
        ),
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('fund_name', models.CharField(default='', max_length=100)),
                ('invested_amount', models.IntegerField(default=0)),
                ('lock_in_period', models.IntegerField(default=0)),
                ('fundplan', models.CharField(choices=[('growth plan', 'growth plan'), ('dividend', 'dividend'), ('dividend reinvestment', 'dividend reinvestment'), ('term', 'term')], max_length=100)),
                ('type', models.CharField(choices=[('One time', 'one time'), ('sip', 'sip')], max_length=100)),
                ('platform', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
