# Generated by Django 4.2 on 2024-11-03 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_familymember_age_mutual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('vehicle_model', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Three Wheeler', 'Three Wheeler'), ('Four Wheeler', 'Four Wheeler')], max_length=50)),
                ('engline_num', models.IntegerField(default=0)),
                ('chasis_num', models.IntegerField(default=0)),
                ('sanctioned_amout', models.IntegerField(default=0)),
                ('term', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
