# Generated by Django 4.2 on 2024-11-03 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_life_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term_Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('policy_holder_name', models.CharField(default='', max_length=100)),
                ('ploicy_no', models.IntegerField(default=0)),
                ('date_of_commencement_of_risk', models.DateField(default=datetime.date.today)),
                ('premium_payment_term', models.CharField(default='', max_length=50)),
                ('premium_payment_mode', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('last_premium_date', models.DateField(default=datetime.date.today)),
                ('critical_illness_beifit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('critical_illness_sumassured', models.IntegerField(default=0)),
                ('accidental_death_benifit', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('accdental_death_beifit_sum_assured', models.IntegerField(default=0)),
                ('return_of_premium', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('joint_life_cover', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('policy_term', models.IntegerField(default='', max_length=100)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('premium_amount', models.IntegerField(default=0)),
                ('sum_assured', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Health_Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('insurance_company', models.CharField(default='', max_length=100)),
                ('employee_code', models.CharField(default='', max_length=100)),
                ('policy_number', models.IntegerField(default=0)),
                ('validity_period_from', models.DateField(default=datetime.date.today)),
                ('validity_period_to', models.DateField(default=datetime.date.today)),
                ('benificiary_name', models.CharField(default='', max_length=100)),
                ('member_id', models.IntegerField(default=0)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('relation', models.CharField(choices=[('Self', 'Self'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=50)),
                ('family_sum_assured', models.IntegerField(default=0)),
                ('balance_sum_assured', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
