# Generated by Django 4.2 on 2024-11-03 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_term_insurance_health_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term_insurance',
            name='policy_term',
            field=models.IntegerField(default=''),
        ),
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0)),
                ('UAN_no', models.IntegerField(default=0)),
                ('PF_number_or_Number_ID', models.CharField(default='', max_length=50)),
                ('upload_UAN_card', models.ImageField(upload_to='images')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
